"""Build the canonical media manifest: which raw files hold each recording's media.

The action grid fixes the canonical ``recording_id`` values; each dataset's
``media_records`` adapter resolves them to files of the media metadata audit.
This module only orchestrates: it converts the paths to corpus-root-relative
form, validates the contract, measures coverage and records lineage. It never
opens a media file and never branches on a dataset name.

```text
vocal action grid ─┐
media metadata  ───┼─> adapter -> media_manifest.parquet (next to the index)
adapter tables  ───┘
```
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import pandas as pd
from omegaconf import DictConfig

from conv_wm.config import PROJECT_ROOT, pipeline_paths
from conv_wm.data import datasets
from conv_wm.data.audits.errors import MissingPrerequisiteError
from conv_wm.data.audits.media_metadata import MEDIA_METADATA_TABLE
from conv_wm.data.media.media_manifest import (
    COLUMN_SEMANTICS,
    MEDIA_SCHEMA_VERSION,
    media_coverage,
    media_manifest_table,
    validate_media_manifest,
)
from conv_wm.data.pipeline.action_grid import GRID_TABLE
from conv_wm.data.pipeline.action_grid import PROCESSED_ROOT as GRID_PROCESSED_ROOT
from conv_wm.data.pipeline.action_grid import REPORT_FILE as GRID_REPORT_FILE
from conv_wm.data.pipeline.action_grid import REPORT_ROOT as GRID_REPORT_ROOT
from conv_wm.data.pipeline.control_state import config_checksum
from conv_wm.data.pipeline_inputs import (
    CheckedArtifact,
    artifact_reference,
    load_checked_artifact,
    sha256_file,
)
from conv_wm.data.vocal.action_grid import ACTION_SCHEMA_VERSION
from conv_wm.provenance import collect_provenance
from conv_wm.reports import JsonDict, write_summary, write_table

logger = logging.getLogger(__name__)

REPORT_SCHEMA_VERSION = 1
REPORT_ROOT = Path("media_manifest")
MEDIA_MANIFEST_TABLE = "media_manifest.parquet"
REPORT_FILE = "report.json"
BUILD_COMMAND = "conv-wm build media-manifest"
GRID_BUILD_COMMAND = "conv-wm build vocal-action-grid"
LINEAGE_CHAIN = (
    "raw media inventory",
    "media metadata audit",
    "vocal action grid (canonical recording ids)",
    "media manifest",
)
PATH_SEMANTICS = (
    "video_path and audio_path are POSIX paths relative to the dataset's corpus "
    "root, the corpus_directory below the raw data root; join them with a "
    "locally configured root. No absolute path is stored."
)
EMBEDDED_AUDIO = (
    "audio_path is set only when the corpus ships a separate audio file; when it "
    "is null and video_has_audio is true, read the audio track of the video "
    "container. No audio file is ever generated by this pipeline."
)


@dataclass(frozen=True)
class MediaManifestOutputs:
    """Manifest and report written for one dataset."""

    dataset: str
    table: pd.DataFrame
    report: JsonDict
    table_path: Path
    report_path: Path

    @property
    def passed(self) -> bool:
        """Whether every labelled canonical recording resolved to media."""
        return self.report["status"] == "PASS"


def supported_datasets() -> tuple[str, ...]:
    """Registered datasets that provide a media adapter."""
    return tuple(spec.name for spec in datasets.iter_specs() if spec.media_records)


def selected_datasets(dataset: str) -> tuple[str, ...]:
    """Expand the CLI selector (``all`` or one supported dataset)."""
    supported = supported_datasets()
    if dataset == "all":
        return supported
    if dataset not in supported:
        raise ValueError(
            f"dataset must be one of {[*supported, 'all']}, got {dataset!r}"
        )
    return (dataset,)


def table_path(cfg: DictConfig, dataset: str) -> Path:
    """Where the manifest of ``dataset`` lives: next to its model-ready index."""
    return pipeline_paths(cfg).model_ready / dataset / MEDIA_MANIFEST_TABLE


def report_path(cfg: DictConfig, dataset: str) -> Path:
    """The report that vouches for the manifest of ``dataset``."""
    return pipeline_paths(cfg).reports / REPORT_ROOT / dataset / REPORT_FILE


def load_grid(cfg: DictConfig, dataset: str) -> CheckedArtifact:
    """Read one dataset's action grid, refusing an input its report disowns."""
    paths = pipeline_paths(cfg)
    return load_checked_artifact(
        dataset=dataset,
        table_path=paths.processed / GRID_PROCESSED_ROOT / dataset / GRID_TABLE,
        report_path=paths.reports / GRID_REPORT_ROOT / dataset / GRID_REPORT_FILE,
        schema_key="action_schema_version",
        expected_version=ACTION_SCHEMA_VERSION,
        artifact_key="grid",
        produce_with=f"{GRID_BUILD_COMMAND} --dataset {dataset}",
    )


def load_media_manifest(cfg: DictConfig, dataset: str) -> CheckedArtifact:
    """Read one dataset's media manifest, refusing a stale or missing one."""
    return load_checked_artifact(
        dataset=dataset,
        table_path=table_path(cfg, dataset),
        report_path=report_path(cfg, dataset),
        schema_key="media_schema_version",
        expected_version=MEDIA_SCHEMA_VERSION,
        artifact_key="media_manifest",
        produce_with=f"{BUILD_COMMAND} --dataset {dataset}",
    )


def media_manifest_for_grid(
    cfg: DictConfig, dataset: str, grid_sha256: str
) -> CheckedArtifact | None:
    """The manifest built from exactly this grid, or ``None`` when none was built.

    A manifest built from another grid is stale and refused, like any other
    input whose checksum no longer matches.
    """
    if not report_path(cfg, dataset).exists():
        return None
    manifest = load_media_manifest(cfg, dataset)
    recorded = manifest.report["input_artifacts"]["vocal_action_grid"]["sha256"]
    if recorded != grid_sha256:
        raise ValueError(
            f"{manifest.table_path} was built from another action grid "
            f"({recorded}); rerun {BUILD_COMMAND} --dataset {dataset}"
        )
    return manifest


def release_card_section(manifest: CheckedArtifact) -> JsonDict:
    """What a dataset card says about the media manifest, with no local path."""
    report = manifest.report
    return {
        "file": MEDIA_MANIFEST_TABLE,
        "sha256": manifest.table_sha256,
        "media_schema_version": report["media_schema_version"],
        "key": ["dataset", "recording_id"],
        "columns": report["columns"],
        "corpus_directory": report["corpus_directory"],
        "path_semantics": report["path_semantics"],
        "embedded_audio": report["embedded_audio"],
        "coverage": {
            key: report["coverage"][key]
            for key in (
                "recordings_in_action_grid",
                "recordings_in_media_manifest",
                "video_available",
                "audio_path_available",
                "recordings_without_resolved_media",
            )
        },
        "raw_media_distributed": False,
    }


def _require(path: Path, command: str) -> Path:
    if not path.exists():
        raise MissingPrerequisiteError(path, produce_with=command)
    return path


def _build_dataset(
    grid: CheckedArtifact,
    media: pd.DataFrame,
    *,
    cfg: DictConfig,
    media_path: Path,
    command: str,
) -> MediaManifestOutputs:
    loader = datasets.get(grid.dataset).media_records
    assert loader is not None
    recordings = sorted(grid.table["recording_id"].astype(str).unique())
    source = loader(cfg, media, recordings)
    table, corpus_directory = media_manifest_table(source)
    validate_media_manifest(table, {(grid.dataset, rid) for rid in recordings})
    valid_slots = grid.table.groupby("recording_id")["action_valid"].sum()
    coverage = media_coverage(
        table,
        recordings,
        source.unresolved,
        {str(rid): int(count) for rid, count in valid_slots.items()},
    )
    status = "FAIL" if coverage["unresolved_with_valid_slots"] else "PASS"

    output_path = write_table(table_path(cfg, grid.dataset), table)
    provenance = collect_provenance()
    uv_lock = PROJECT_ROOT / "uv.lock"
    payload: JsonDict = {
        "build_type": "media_manifest",
        "schema_version": REPORT_SCHEMA_VERSION,
        "media_schema_version": MEDIA_SCHEMA_VERSION,
        "source_action_schema_version": ACTION_SCHEMA_VERSION,
        "dataset": grid.dataset,
        "created_at": provenance.generated_at_utc,
        "git_commit": provenance.git_commit,
        "git_dirty": provenance.git_dirty,
        "command": command,
        "config_checksum": config_checksum(cfg),
        "lineage_chain": list(LINEAGE_CHAIN),
        "input_artifacts": {
            "vocal_action_grid": {
                "path": str(grid.table_path),
                "sha256": grid.table_sha256,
            },
            "vocal_action_grid_report": {
                "path": str(grid.report_path),
                "sha256": grid.report_sha256,
            },
            "media_metadata": artifact_reference(media_path),
            "adapter_tables": [artifact_reference(path) for path in source.input_paths],
        },
        "uv_lock_checksum": sha256_file(uv_lock) if uv_lock.exists() else None,
        "output_artifacts": {"media_manifest": artifact_reference(output_path)},
        "columns": COLUMN_SEMANTICS,
        "corpus_directory": corpus_directory,
        "path_semantics": PATH_SEMANTICS,
        "embedded_audio": EMBEDDED_AUDIO,
        "adapter_mapping": source.mapping,
        "coverage": coverage,
        "status": status,
        "status_rule": (
            "FAIL when a canonical recording with labelled (action_valid) slots "
            "has no resolved media; recordings the grid already masks entirely "
            "are reported but tolerated"
        ),
    }
    path = report_path(cfg, grid.dataset)
    report = write_summary(path, payload, provenance=provenance)
    return MediaManifestOutputs(grid.dataset, table, report, output_path, path)


def run_media_manifest_build(
    cfg: DictConfig,
    *,
    dataset: str = "all",
    command: str | None = None,
) -> list[MediaManifestOutputs]:
    """Build the media manifest of every selected dataset."""
    media_path = _require(
        pipeline_paths(cfg).reports / MEDIA_METADATA_TABLE, "conv-wm audit media"
    )
    media = pd.read_parquet(media_path)
    invoked = command or f"{BUILD_COMMAND} --dataset {dataset}"
    outputs: list[MediaManifestOutputs] = []
    for name in selected_datasets(dataset):
        grid = load_grid(cfg, name)
        output = _build_dataset(
            grid, media, cfg=cfg, media_path=media_path, command=invoked
        )
        logger.info("%s: %d media records", name, len(output.table))
        outputs.append(output)
    return outputs


def format_outputs(outputs: list[MediaManifestOutputs]) -> str:
    """The per-dataset coverage a generation run prints."""
    lines: list[str] = []
    for output in outputs:
        coverage = output.report["coverage"]
        lines.append(f"[{output.dataset}] media manifest: {output.report['status']}")
        for key in (
            "recordings_in_action_grid",
            "recordings_in_media_manifest",
            "video_available",
            "audio_path_available",
            "video_only",
            "audio_only",
            "both",
            "video_with_embedded_audio",
            "recordings_without_resolved_media",
        ):
            lines.append(f"  {key.replace('_', ' ')}: {coverage[key]}")
        if coverage["unresolved_reasons"]:
            lines.append(f"  unresolved reasons: {coverage['unresolved_reasons']}")
        if coverage["unresolved_with_valid_slots"]:
            lines.append(
                "  [FAILED] labelled recordings without media: "
                f"{coverage['unresolved_with_valid_slots'][:10]}"
            )
        lines.append(f"  manifest: {output.table_path}")
        lines.append(f"  report:   {output.report_path}")
    return "\n".join(lines)


__all__ = [
    "MEDIA_MANIFEST_TABLE",
    "MediaManifestOutputs",
    "format_outputs",
    "load_media_manifest",
    "media_manifest_for_grid",
    "release_card_section",
    "run_media_manifest_build",
    "selected_datasets",
    "supported_datasets",
]
