"""Generate the label reference page from the registry, so the two never drift.

``conv-wm labels docs`` writes :data:`DOC_PATH`; a test fails whenever the
committed page differs from what the registry generates.
"""

from __future__ import annotations

from collections.abc import Mapping

from conv_wm.config import PROJECT_ROOT
from conv_wm.data import datasets
from conv_wm.data.labels.catalog import REGISTRY
from conv_wm.data.labels.registry import (
    FAMILIES,
    LABEL_SCHEMA_VERSION,
    REGISTRY_VERSION,
    LabelSpec,
)

DOC_PATH = PROJECT_ROOT / "docs" / "data_pipeline" / "labels_registry.md"


def dataset_facts() -> dict[str, frozenset[str]]:
    """Facts each registered dataset declares for labels."""
    return {
        spec.name: spec.label_facts.provides
        for spec in datasets.iter_specs()
        if spec.label_facts is not None
    }


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _support(spec: LabelSpec, facts: Mapping[str, frozenset[str]]) -> str:
    if spec.extractor is None:
        return "—"
    supported = [
        name for name, provided in facts.items() if spec.supported_by(provided)
    ]
    return ", ".join(supported) if supported else "none registered"


def registry_markdown() -> str:
    """The whole reference page."""
    facts = dataset_facts()
    names = sorted(facts)
    lines = [
        "# Label registry (generated)",
        "",
        (
            "<!-- Generated by `conv-wm labels docs` from "
            "`src/conv_wm/data/labels/catalog.py`. Do not edit by hand. -->"
        ),
        "",
        (
            f"Registry version {REGISTRY_VERSION}, label schema version "
            f"{LABEL_SCHEMA_VERSION}. {len(REGISTRY)} labels, "
            f"{sum(s.extractor is not None for s in REGISTRY)} materializable. "
            "How to read, build and request them: [`labels.md`](labels.md)."
        ),
        "",
        "## Support matrix",
        "",
        "| label | source kind | modalities | level | " + " | ".join(names) + " |",
        "| --- | --- | --- | --- | " + " | ".join("---" for _ in names) + " |",
    ]
    for spec in REGISTRY:
        marks = ["yes" if spec.supported_by(facts[name]) else "—" for name in names]
        lines.append(
            f"| `{spec.name}` | {spec.source_kind} | "
            f"{', '.join(map(str, spec.modalities))} | {spec.level} | "
            + " | ".join(marks)
            + " |"
        )
    lines += [
        "",
        "Dataset facts: "
        + "; ".join(f"**{name}** {', '.join(sorted(facts[name]))}" for name in names)
        + ".",
    ]
    for family, purpose in FAMILIES.items():
        specs = [spec for spec in REGISTRY if spec.family == family]
        lines += ["", f"## `{family}` — {purpose}", ""]
        for spec in specs:
            lines += [
                f"### `{spec.name}`",
                "",
                _cell(spec.description),
                "",
                f"- **availability**: {spec.availability}"
                + (
                    f" — {_cell(spec.unsupported_reason)}"
                    if spec.unsupported_reason
                    else ""
                ),
                f"- **source kind**: {spec.source_kind}; **role**: {spec.role}",
                f"- **modalities**: {', '.join(map(str, spec.modalities))}",
                f"- **level**: {spec.level}; **dtype**: `{spec.dtype}`; **shape**: `{spec.shape}`",
                f"- **time**: {_cell(spec.time_reference)}",
                f"- **validity**: {_cell(spec.validity)}",
            ]
            if spec.extractor is not None:
                storage = (
                    f"`{spec.extractor}/{spec.table}.parquet` columns "
                    + ", ".join(f"`{c}`" for c in spec.columns)
                )
                if spec.row_filter:
                    storage += f" (rows where `{spec.row_filter[0]} == {spec.row_filter[1]!r}`)"
                lines.append(f"- **storage**: {storage}")
                lines.append(
                    f"- **requires**: {', '.join(spec.requires) or 'nothing'}; "
                    f"**datasets**: {_support(spec, facts)}"
                )
            if spec.external is not None and spec.external.package is not None:
                tool = spec.external
                lines.append(
                    f"- **external tool**: {tool.tool} (`{tool.package}`"
                    + (f", extra `{tool.extra}`" if tool.extra else "")
                    + f"); licence: {_cell(tool.license)}; determinism: "
                    f"{_cell(tool.determinism)}"
                )
            if spec.notes:
                lines.append(f"- **notes**: {_cell(spec.notes)}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


__all__ = ["DOC_PATH", "dataset_facts", "registry_markdown"]
